/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hobbytecaGUI;

import static hobbytecaGUI.HobbyTeca.controller;
import static hobbytecaGUI.HobbyTeca.rs;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author kevin
 */
public class Estadistica extends javax.swing.JDialog {

    /**
     * Creates new form Estadistica
     * @param parent
     * @param modal
     * @throws java.sql.SQLException
     */
    public Estadistica(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        rellenarTextArea();
    }

    private void rellenarTextArea() throws SQLException{
        String resultado = "Total de Contenido = ";
        rs = controller.EjecutarSentencia("SELECT COUNT(*) FROM MULTILISTA");
        rs.next();
        resultado += rs.getInt(1) + "\n";
        rs = controller.EjecutarSentencia("SELECT COUNT(*) FROM MULTILISTA WHERE clase = 'PC'");
        rs.next();
        resultado += "PC = " + rs.getInt(1) + "\n";
        rs = controller.EjecutarSentencia("SELECT COUNT(*) FROM MULTILISTA WHERE clase = 'PS4'");
        rs.next();
        resultado += "PS4 = " + rs.getInt(1) + "\n";
        rs = controller.EjecutarSentencia("SELECT COUNT(*) FROM MULTILISTA WHERE clase = 'Película'");
        rs.next();
        resultado += "Películas = " + rs.getInt(1) + "\n";
        rs = controller.EjecutarSentencia("SELECT COUNT(*) FROM MULTILISTA WHERE clase = 'Película [Anime]'");
        rs.next();
        resultado += "Películas [Anime] = " + rs.getInt(1) + "\n";
        rs = controller.EjecutarSentencia("SELECT COUNT(*) FROM MULTILISTA WHERE clase = 'Serie'");
        rs.next();
        resultado += "Series = " + rs.getInt(1) + "\n";
        rs = controller.EjecutarSentencia("SELECT COUNT(*) FROM MULTILISTA WHERE clase = 'Anime'");
        rs.next();
        resultado += "Animes = " + rs.getInt(1) + "\n";
        jTextArea1.setText(resultado);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            Estadistica dialog = null;
            try {
                dialog = new Estadistica(new javax.swing.JFrame(), true);
            } catch (SQLException ex) {
                Logger.getLogger(Estadistica.class.getName()).log(Level.SEVERE, null, ex);
            }
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
